[build-system]
requires = ["setuptools>59", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "psychopy-eyetracker-eyelink"
version = "0.0.1"
description = "Extension package for PsychoPy which adds support for EyeLink eyetrackers."
readme = "README.md"
requires-python = ">= 3.7"
license = {text = "GNU General Public License v3 (GPLv3)"}
authors = [
  { name = "Oscar Esteban", email = "code@oscaresteban.es" }
]
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]
urls.homepage = "https://github.com/oesteban/psychopy-eyetracker-eyelink"
urls.changelog = "https://github.com/oesteban/psychopy-eyetracker-eyelink/blob/main/CHANGELOG.txt"
urls.repository = "https://github.com/oesteban/psychopy-eyetracker-eyelink"
dependencies = []
[tool.setuptools.packages.find]
where = ["", "psychopy_eyetracker_sr_research",]

[tool.setuptools.package-data]
"*" = ["*.yaml"]
